#53
foaudkajj/inventory-management-ws pull request #33
Opened 2023-08-11 14:29 UTC by ibrahim-Pasha

2023-08-12 05:40 UTC, foaudkajj requested changes
Please check the notes

2023-08-12 05:40 UTC, foaudkajj commented on src/endpoints/unit/sell-products/selling-controller.ts
> +              this.saleService.insert(sale);
Don't forget to `await` the promises.

2023-08-12 05:40 UTC, foaudkajj commented on src/endpoints/unit/sell-products/selling-controller.ts
> +            ) {
Use if(not valid) and throw an error immediately.

2023-08-12 05:40 UTC, foaudkajj commented on src/endpoints/unit/sell-products/selling-controller.ts
> +    const paymentMethods = await this.paymentMethodService.getAll();
Use promise.all to load the products and payment methods (better performance)

2023-08-12 05:40 UTC, foaudkajj commented on src/endpoints/unit/sell-products/selling-controller.ts
> +        .reduce((accumulator, currentValue) => accumulator + currentValue)
Extract long code into a new variable to have a clean/readable code.

2023-08-12 05:40 UTC, foaudkajj commented on src/endpoints/unit/sell-products/selling-controller.ts
> +        .reduce((accumulator, currentValue) => accumulator + currentValue) >= 1
Extract long code into a new variable to have a clean/readable code.
The same rule applies to the other code.

2023-08-12 05:40 UTC, foaudkajj commented on src/endpoints/unit/sell-products/selling-controller.ts
> +    const products = await this.productService.getAll();
Create a new method in the ProductService called `getByIds(ids:string[])` and load only ids available in the request. Read about [In](https://typeorm.io/find-options#advanced-options)

2023-08-12 05:40 UTC, foaudkajj commented on src/endpoints/unit/sell-products/selling-controller.ts
> +              .includes(saleRequest.products.find(x => x).productId)
What is the meaning of this?

2023-08-12 05:40 UTC, foaudkajj commented on src/endpoints/unit/sell-products/selling-controller.ts
> +                  saleRequest.paymentMethods.find(x => x).paymentMethodId,
What is the meaning of this?

2023-08-12 05:40 UTC, foaudkajj commented on src/endpoints/unit/sell-products/selling-controller.ts
> +                  (saleProduct.sellingPrice = product.sellingPrice),
Why there are parantheses around the lines?

2023-08-12 05:43 UTC, foaudkajj requested changes

2023-08-12 05:43 UTC, foaudkajj commented on src/endpoints/unit/sell-products/selling-controller.ts
> +                }
Create a list of `SalePaymentMethod` class and insert all of them in one go. (Do the same with the other inserts)

2023-08-12 07:36 UTC, ibrahim-Pasha commented on src/endpoints/unit/sell-products/selling-controller.ts
> +              .includes(saleRequest.products.find(x => x).productId)
the sum of amunt will be more then 0

2023-08-14 09:43 UTC, foaudkajj commented on src/endpoints/unit/sell-products/selling-controller.ts
> +            throw new error('product.id-not-valid');
use `Error` instead of `error`

2023-08-14 09:44 UTC, foaudkajj commented on src/endpoints/unit/sell-products/selling-controller.ts
> +        this.salePaymentMethodService.insert(salepaymentMethods);
Use `await` here. call me to explain why.

2023-08-14 10:40 UTC, foaudkajj approved these changes

2023-08-14 10:40 UTC, merged